### ISSUE TITLE
Slipperiness commands don't work in command blocks

### ISSUE THREAD

**Issue by skrabyz** [o7Moon/OpenBoatUtils#44]
I wanted to set up a row of command blocks in the lobby to change the cc / engine class like in most racing games if players wanted to race on the tracks at a slower speed (or faster if they're crazy enough to try), but when I hooked up the command blocks, they didn't work. Double checked for typos and there are none. Only tested on a single player world.

**Comment by o7Moon** [comment]
the singleplayer commands only apply to the sender of the command, so nothing happens when a command block runs them. you should be able to use `execute as ____ run /defaultslipperiness ____` from a command block to run the commands as a player
