### ISSUE TITLE
support newer mc versions

### ISSUE THREAD

**Issue by o7Moon** [o7Moon/OpenBoatUtils#45]
1.20.2 seems to work as is, the mod json just needs to be edited to include it. need to test more thoroughly and with more versions to see if any other changes are necessary.

**Comment by Pepsied-5229** [comment]
I'm very interested in this mod. I'd really appreciate it if I can use the mod on 1.20.2 or 1.20.X. Is modification of a looser version check in the mod JSON planned?

**Comment by o7Moon** [comment]
planning on 1.20.1-1.20.4 for 0.4
