### ISSUE TITLE
Falldamage rule ignored at specific heights (dedicated server)

### ISSUE THREAD

**Issue by muggelpotato** [o7Moon/OpenBoatUtils#60]
I tested various heights (level surface) and found that at specific heights the boat would break even with the falldamage rule set to false.
Sometimes it wont break as long as you're moving.

Affected jumpforce values (tested with .1 steps, from 0-1.5):

- 0.6 (4 blocks)
- 0.8 (7.5 blocks)
- 1 (12 blocks)
- 1.1 (14.5 blocks)
- 1.2 (17 blocks)
- 1.5 (27 blocks)

Sometimes changing values by .01 fixes the issue. 
You need to tap W again after landing to break the boat.
Only breaks when jumping. Falling from same heights doesn't break the boat. 
Might be a desync issue. Server is overspec and I have low ping if that helps.

Thoughts:
Jumping probably brings you to certain decimal heights that just kill the boat anyway because it accelerates to a specific speed. Just falling from equal heights (flat values) might work fine because it doesn't accelerates to that specific downwards acceleration that ignores the gamerule and therefore destroys the boat.

But all in all a really really fun mod. I wish we had it back then when friends still had time to play.

**Comment by muggelpotato** [comment]
nvmd fixed it with [https://modrinth.com/mod/boat-break-fix](url)

Still would be nice if that feature would be fixed in the future.

**Comment by o7Moon** [comment]
my theory here is the boat is breaking serverside, obu prevents it from happening on the client but if the server says the boat breaks then it breaks. something like boat-break-fix works here because it runs on the server too. I could do something similar for obu but its really made for other mods and/or plugins to take advantage of rather than being used standalone

**Comment by muggelpotato** [comment]
I ran obu for testing reasons on the server. Would be nice if running commands from the server console would set them default globaly. Something like if server executes command it applies to @a as default even on reconnect or first join.
