### ISSUE TITLE
Mod wont work in 1.20.4 Aternos server.

### ISSUE THREAD

**Issue by ReapDaReaper** [o7Moon/OpenBoatUtils#61]
commands appear but nothing is changed even after I set the commands.

**Comment by o7Moon** [comment]
Are you running the mod on your client? The server commands are mainly for testing, OpenBoatUtils is meant to extend the client so that *other* server mods/plugins can take advantage of it, but the commands should work if you have the mod installed on both. If not, let me know and ill look into it.

**Comment by uczpre** [comment]
@o7Moon you should clarify that on the mod page ;D
